### ISSUE TITLE
if front-page customization not entered, exceptions

### ISSUE THREAD

**Issue by earlofhemsley** [landon-hemsley/chic#6]
make sure on first time load of home page that if the category is not found (i.e. set to null) that it doesn't crap out.

Notice: Undefined property: WP_Error::$taxonomy in /home2/gownsbyl/public_html/sewchicpatterns/wp-content/themes/sewchic/template-parts/home/feed.php on line 16

Notice: Undefined property: WP_Error::$term_id in /home2/gownsbyl/public_html/sewchicpatterns/wp-content/themes/sewchic/template-parts/home/feed.php on line 18

Notice: Undefined property: WP_Error::$taxonomy in /home2/gownsbyl/public_html/sewchicpatterns/wp-content/themes/sewchic/template-parts/home/feed.php on line 31

Fatal error: Uncaught exception 'Exception' with message 'Could not load posts for this category' in /home2/gownsbyl/public_html/sewchicpatterns/wp-content/themes/sewchic/template-parts/home/feed.php:37 Stack trace: #0 /home2/gownsbyl/public_html/sewchicpatterns/wp-includes/template.php(690): require() #1 /home2/gownsbyl/public_html/sewchicpatterns/wp-includes/template.php(647): load_template('/home2/gownsbyl...', false) #2 /home2/gownsbyl/public_html/sewchicpatterns/wp-includes/general-template.php(155): locate_template(Array, true, false) #3 /home2/gownsbyl/public_html/sewchicpatterns/wp-content/themes/sewchic/home.php(27): get_template_part('template-parts/...') #4 /home2/gownsbyl/public_html/sewchicpatterns/wp-includes/template-loader.php(74): include('/home2/gownsbyl...') #5 /home2/gownsbyl/public_html/sewchicpatterns/wp-blog-header.php(19): require_once('/home2/gownsbyl...') #6 /home2/gownsbyl/public_html/sewchicpatterns/index.php(17): require('/home2/gownsbyl...') #7 {main} thrown in /home2/gownsbyl/public_html/sewchicpatterns/wp-content/themes/sewchic/template-parts/home/feed.php on line 37

**Comment by earlofhemsley** [comment]
This should be fixed. Very hard to test.
